export enum IngredientCategory {
  MEAT = 'meat',
  POULTRY = 'poultry',
  SEAFOOD = 'seafood',
  EGGS = 'eggs',
  DAIRY = 'dairy',
  VEGETABLES = 'vegetables',
  FRUITS = 'fruits',
  LEGUMES = 'legumes',
  GRAINS = 'grains',
  FLOUR = 'flour',
  BREAD_BAKERY = 'bread_bakery',
  HERBS_SPICES = 'herbs_spices',
  SAUCES_CONDIMENTS = 'sauces_condiments',
  OILS_FATS = 'oils_fats',
  BEVERAGES = 'beverages',
  ALCOHOLIC = 'alcoholic',
  FROZEN = 'frozen',
  CANNED = 'canned',
  DESSERT_SWEETS = 'dessert_sweets',
  OTHER = 'other',
}

export const IngredientCategoryLabels: Record<IngredientCategory, string> = {
  [IngredientCategory.MEAT]: 'Carnes y Cerdo',
  [IngredientCategory.POULTRY]: 'Aves',
  [IngredientCategory.SEAFOOD]: 'Pescados y Mariscos',
  [IngredientCategory.EGGS]: 'Huevos',
  [IngredientCategory.DAIRY]: 'Lácteos y Quesos',
  [IngredientCategory.VEGETABLES]: 'Vegetales',
  [IngredientCategory.FRUITS]: 'Frutas',
  [IngredientCategory.LEGUMES]: 'Legumbres',
  [IngredientCategory.GRAINS]: 'Granos y Pastas',
  [IngredientCategory.FLOUR]: 'Harinas',
  [IngredientCategory.BREAD_BAKERY]: 'Panadería',
  [IngredientCategory.HERBS_SPICES]: 'Hierbas y Especias',
  [IngredientCategory.SAUCES_CONDIMENTS]: 'Salsas y Condimentos',
  [IngredientCategory.OILS_FATS]: 'Aceites y Grasas',
  [IngredientCategory.BEVERAGES]: 'Bebidas',
  [IngredientCategory.ALCOHOLIC]: 'Bebidas Alcohólicas',
  [IngredientCategory.FROZEN]: 'Congelados',
  [IngredientCategory.CANNED]: 'Enlatados',
  [IngredientCategory.DESSERT_SWEETS]: 'Postres y Dulces',
  [IngredientCategory.OTHER]: 'Otros',
};
