export enum HTTP_STATUS {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
}

export const COMMON_MESSAGE = {
  [HTTP_STATUS.INTERNAL_SERVER_ERROR]: '¡Ups! Algo salió mal',
};
